//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public string Food1 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Delivery_price { get; set; }
    }
}
